### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [sokolik90/sokolik90.github.io#1]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий
**Нужно исправить**: README файл должен содержать номер версии (ненулевой), **активную ссылку на проект (github pages)** и заголовок **отражающий назначение проекта**.
**Нужно исправить** схема ветвления не соответствует требования задания.
В репозитории должны быть следующие ветки - master, develop, gh-pages

## Регулярные выражения
**Можно лучше** Квантификатор `{1}` можно не использовать. Он не играет никакой роли.
**Можно лучше** Квантификатор `{1,}` можно заменить на `+` - он означает "один или более"

### Имя 
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`Ёлка----------` - в имени может быть только один дефис
`Денис-ловеркейс` - второе имя должно быть с заглавной буквы

### Email
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`my---mail@site.ru` - адрес электронной почты, содержащий несколько символов '-' подряд является некорректным

### Номер телефона
**Нужно исправить** следующие корректные кейсы не проходят валидацию
```
+7(925)900-90-90
+7(925) 900-90-90
+7 925-900-90-90
```

**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.
```
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
```

### Адрес сайта
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`http://www.ya.` - отсутствует доменна зона 
`http://127.0..`  - некорректный IP, точка на конце
`http://127.0.0..` - некорректный IP, точка на конце)
`http://127.0.0.1:8000/$ssss@#` - некорректный путь - разрешены только цифры, слеш и латинские буквы, решетка (#) на конце) 
https://mysite.23 (tld не может состоять из цифр)

**Comment by zlocate** [comment]
## Регулярные выражения

**Данные кейсы, отмеченные на прошлой итерации к сожалению не исправлены в текущей версии, размещенной на Github Pages. Пожалуйста, убедитесь что все изменения попали в ветку gh-pages**

**Можно лучше** Квантификатор `{1}` можно не использовать. Он не играет никакой роли.
**Можно лучше** Квантификатор `{1,}` можно заменить на `+` - он означает "один или более"

### Имя 
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`Ёлка----------` - в имени может быть только один дефис
`Денис-ловеркейс` - второе имя должно быть с заглавной буквы


### Email
Регулярное выражение, предназначенное для валидации email содержит синтаксическую ошибку, связанную с избыточным экранированием,
http://i.imgur.com/seT6Vqv.png

**Нужно исправить** следующие некорректные кейсы проходят валидацию
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`my---mail@site.ru` - адрес электронной почты, содержащий несколько символов '-' подряд является некорректным

### Адрес сайта
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`http://www.ya.` - отсутствует доменна зона 
`http://127.0..`  - некорректный IP, точка на конце
`http://127.0.0..` - некорректный IP, точка на конце)
`http://127.0.0.1:8000/$ssss@#` - некорректный путь - разрешены только цифры, слеш и латинские буквы, решетка (#) на конце) 
https://mysite.23 (tld не может состоять из цифр)

**Comment by zlocate** [comment]
Добрый день. Остался один кейс, требующий исправления.

### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`some-extra-long-name@some.extra.long.domain.name` - адрес почты может содержать произвольное число поддоменов

**Comment by zlocate** [comment]
Добрый вечер. Работа принята. Желаю успехов в дальнейшем прохождении курса

**Comment by free-flying-bird** [comment]
Project is closed
